### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by xmskf** [hadoopsubmarine/hadoop-submarine-ecosystem#1]
Hello engineer：

System： Centos 6.7

1、git clone project
2、cd hadoop-submarine-ecosystem/submarine-installer
3、sh install.sh

When I operate the above steps, the problem appears. How can I solve it?Thank you very much!

**Comment by xmskf** [comment]
您好，我刚才敲错系统版本了，其实是：CentOS Linux release 7.6.1810 (Core)。

**Comment by xmskf** [comment]
您好，我刚输入了错误的系统版本。实际上，它是CentOS Linux版本7.6.1810（核心版）。
另一个问题是我没有NVDIA的GPU，请问是否可以部署？

**Comment by xmskf** [comment]
Thank you!
Sorry, I just typed the wrong version of the system, actually: CentOS Linux release 7.6.1810 (Core).
Another question is that I do not have the GPU of NVDIA, may I ask whether it can be deployed?

**Comment by xmskf** [comment]
还有我刚才查看文档的时候发现：
![Alt text](https://raw.githubusercontent.com/xmskf/Picture/master/TIM截图20190129095242.png)
请问下，这个是不是错误的？

**Comment by liuxunorg** [comment]
These `users` and `groups` are the accounts that are required to run YARN in Linux. So you have to add it.
This installation script is a scripting tool used in our production environment and is tested and is no problem.

**Comment by liuxunorg** [comment]
你也可以扫描二维码，进微信群讨论问题。

![alt text](https://github.com/liuxunorg/images/blob/master/hadoopsubmarine/weixin-group.png?raw=true "weixin-group.png")

**Comment by xmskf** [comment]
收到，谢谢！
