### ISSUE TITLE
个人意见仅供参考

### ISSUE THREAD

**Issue by Sinever** [hadoopsubmarine/hadoop-submarine-ecosystem#2]
1.它允许 Hadoop 支持 Tensorflow，MXNet，Caffe，Spark 等各种深度学习框架这里Spark不是深度学习框架
2.分布式模型培训应该是分布式模型训练，中文是用机器翻译的有些要自己改改，不是很通顺
3.在安装部署好 Hadoop 3.1+ 和 Zeppelin 后，Submarine 将为每个用户在 YARN 中创建一个完全独立的 Zeppelin Submarine interpreter Docker 容器 安装好hadoop3.1后和Submarine为每个用户创建sumarine的interpreter docker容器中间还有很多工作要做，比如安装docker，安装calico，让hadoop支持docker调度，安装submarine等，主要是这里的安装好的好字概括的太多，可以吧安装手册的链接放这里，另外对zeppelin也有版本要求吧。
4.Zeppelin Submarine interpreter架构图最后的job run落后了，下面已经是dashboard了。
5.Submarine interpreter Docker Image 是由 Submarine 为你提供支持 Tensorflow （CPU 和 GPU 版本）的镜像文件 重复了两遍
6.submarine.algorithm.hdfs.path参数的解释不太对，应该是保存的路径。

**Comment by hadoopsubmarine** [comment]
Thanks for your suggestion, We have updated the documentation. Tanks!
