### ISSUE TITLE
个人意见

### ISSUE THREAD

**Issue by Sinever** [hadoopsubmarine/hadoop-submarine-ecosystem#3]
You can use the more than 20 interpreters in zeppelin (for example: spark, hive, Cassandra, Elasticsearch, Kylin, HBase, etc.) to collect data, zeppelin好像没有数据采集功能？

**Comment by hadoopsubmarine** [comment]
Did you say that the data collection function refers to the data ETL?
You can use spark to get data from HDFS for data processing and write back to HDFS. then give it to submarine for machine learning.

**Comment by Sinever** [comment]
ok, in my opinion, "collect data" means collecting data from devices/webpages/etc. that's ok.
