### ISSUE TITLE
关于J环境和cgroup权限问题

### ISSUE THREAD

**Issue by BlodwenZ** [hadoopsubmarine/hadoop-submarine-ecosystem#5]
@liuxunorg 
你好，
近期我在根据您的文档安装submarine。 我有几个问题和您探讨一下，
首先环境，
1. 我使用的etcd flannel还有CDH里的yarn 是否也满足安装要求？
2. 如果网络组件一定要用calico，可不可以安装在host上而不是在运行在container里？
其次关于cgroup的权限问题，
我想请问一定要改权限才能配置成功吗？
希望能得到你在百忙之中的解答。
谢谢~

**Comment by liuxunorg** [comment]
BlodwenZ, 你好:

1. 我们测试过的网络组件是 ETCD，我们估计只要你正确的安装 flannel ，应该也是可以的。
2. 我们目前使用的是 Hadoop Submarine 是 hadoop 3.3.0 版本中的 YARN，我不确定CDH中的版本。
3. calico 本来就是安装在 host 上，不是安装在 container里。
4. cgroup的权限问题，你可以参考使用我们提供的 https://github.com/hadoopsubmarine/submarine-installer 中的安装程序，这是经过生产环境验证的。

另外，你可以扫描微信二维码，欢迎进入 Hadoop Submarine 的用户群，一起探讨问题。
![WechatIMG1](https://user-images.githubusercontent.com/3677382/54749281-08f4eb80-4c0f-11e9-898d-ac7fa988c223.jpeg)
